-- Optional seed data for local development.
-- The main project data is generated by apps/data_generator/main.py.
-- This file is intentionally kept minimal so SQL validation does not fail.

SELECT 1 AS seed_file_ready;